[versions]
agp = "8.13.0"
fragmentKtx = "1.8.9"
fragmentKtxVersion = "1.8.9"
gson = "2.13.2"
gsonVersion = "2.13.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
generativeai = "0.9.0"
navigationFragmentKtx = "2.9.6"
navigationFragmentKtxVersion = "2.9.6"
navigationUiKtx = "2.9.6"
roomKtx = "2.8.3"
compiler = "3.2.0-alpha11"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
#noinspection SimilarGradleDependency
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
#noinspection SimilarGradleDependency
androidx-fragment-ktx-v188 = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtxVersion" }
#noinspection SimilarGradleDependency
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
#noinspection SimilarGradleDependency
androidx-navigation-fragment-ktx-v292 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
#noinspection SimilarGradleDependency
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
#noinspection SimilarGradleDependency
androidx-navigation-ui-ktx-v292 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-navigation3-ui-ktx = { module = "androidx.navigation3:navigation3-ui-ktx" }
#noinspection SimilarGradleDependency
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
#noinspection SimilarGradleDependency
gson-v2110 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-compiler = { group = "androidx.databinding", name = "compiler", version.ref = "compiler" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

